### ISSUE TITLE
add companies icons next to each other as per the given design

### ISSUE THREAD

**Issue by subrat611** [snehabarua/cloned_page#1]
##  Fix the design for galaxy S8+

![image](https://user-images.githubusercontent.com/77252075/221334875-757aba97-74fa-409f-9ee1-fcdda7d0fcf1.png)

**Comment by snehabarua** [comment]
![image](https://user-images.githubusercontent.com/88395976/221348939-b33477de-9c07-482b-927d-5cde95b091ce.png)
Tried my best!!

**Comment by subrat611** [comment]
Good 👍️
