### ISSUE TITLE
The alt attribute should never be empty

### ISSUE THREAD

**Issue by subrat611** [snehabarua/cloned_page#2]
## Give a value in alt attribute

`<img src="Assets/Netflix Logo.svg" alt="" />
 <img src="Assets/Shopify Logo.svg" alt="" />
 <img src="Assets/Spotify Logo.svg" alt="" />
 <img src="Assets/Walmart Logo.svg" alt="" />`

**Comment by snehabarua** [comment]
Added an alt texts for every image.

**Comment by subrat611** [comment]
Done
